from __future__ import annotations

from contextlib import contextmanager

from config import SETTINGS


PROFILE_OVERRIDES: dict[str, dict[str, object]] = {
    "balanced": {},
    "trend": {
        "mean_reversion_enabled": False,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": True,
        "require_nonnegative_rl": True,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.52,
        "entry_prob_buffer": 0.01,
        "entry_min_volume_ratio": 0.95,
        "entry_max_atr_pct": 0.006,
    },
    "mean_reversion": {
        "btc_mean_reversion_only": True,
        "mean_reversion_enabled": True,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": False,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.50,
        "entry_prob_buffer": 0.005,
        "entry_min_volume_ratio": 0.95,
        "entry_max_atr_pct": 0.007,
        "mean_reversion_prob_floor": 0.54,
        "mean_reversion_rsi_delta_min": 1.5,
        "mean_reversion_min_prob_up": 0.58,
        "mean_reversion_edge_min_margin": 0.04,
    },
    "btc_5m_range": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": True,
        "mean_reversion_enabled": True,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": False,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.56,
        "entry_prob_buffer": 0.010,
        "entry_min_volume_ratio": 1.05,
        "entry_max_atr_pct": 0.010,
        "mean_reversion_prob_floor": 0.62,
        "mean_reversion_rsi_max": 36.0,
        "mean_reversion_bb_pos_max": 0.12,
        "mean_reversion_range_pos_max": 0.16,
        "mean_reversion_return_5_min": -0.010,
        "mean_reversion_atr_pct_max": 0.012,
        "mean_reversion_rsi_delta_min": 2.0,
        "mean_reversion_body_pct_min": 0.25,
        "mean_reversion_lower_wick_min": 0.40,
        "mean_reversion_price_vs_ema20_max": -0.003,
        "mean_reversion_min_close_location": 0.55,
        "mean_reversion_min_signed_volume_proxy": 0.05,
        "mean_reversion_min_prob_up": 0.64,
        "mean_reversion_min_model_prob_up": 0.50,
        "mean_reversion_edge_min_margin": 0.07,
    },
    "btc_5m_breakout": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": False,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": True,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.58,
        "entry_prob_buffer": 0.015,
        "entry_min_volume_ratio": 1.20,
        "entry_max_atr_pct": 0.012,
        "breakout_max_bb_width": 0.018,
        "breakout_min_breakout_up_20": 0.0015,
        "breakout_min_volume_ratio": 1.20,
        "breakout_min_close_location": 0.70,
        "breakout_min_range_efficiency": 0.55,
        "breakout_min_signed_volume_proxy": 0.20,
        "breakout_min_price_vs_ema20": 0.0005,
        "breakout_prob_floor": 0.62,
    },
    "alt_5m_breakout": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": False,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": True,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.60,
        "entry_prob_buffer": 0.015,
        "entry_min_volume_ratio": 1.25,
        "entry_max_atr_pct": 0.014,
        "breakout_max_bb_width": 0.020,
        "breakout_min_breakout_up_20": 0.0020,
        "breakout_min_volume_ratio": 1.25,
        "breakout_min_close_location": 0.72,
        "breakout_min_range_efficiency": 0.58,
        "breakout_min_signed_volume_proxy": 0.24,
        "breakout_min_price_vs_ema20": 0.0008,
        "breakout_prob_floor": 0.64,
    },
    "alt_5m_pullback": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": True,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": False,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.57,
        "entry_prob_buffer": 0.010,
        "entry_min_volume_ratio": 1.00,
        "entry_max_atr_pct": 0.012,
        "mean_reversion_prob_floor": 0.61,
        "mean_reversion_rsi_max": 39.0,
        "mean_reversion_bb_pos_max": 0.16,
        "mean_reversion_range_pos_max": 0.22,
        "mean_reversion_return_5_min": -0.007,
        "mean_reversion_atr_pct_max": 0.012,
        "mean_reversion_rsi_delta_min": 1.7,
        "mean_reversion_body_pct_min": 0.18,
        "mean_reversion_lower_wick_min": 0.32,
        "mean_reversion_price_vs_ema20_max": -0.0025,
        "mean_reversion_min_close_location": 0.46,
        "mean_reversion_min_signed_volume_proxy": 0.03,
        "mean_reversion_min_prob_up": 0.62,
        "mean_reversion_min_model_prob_up": 0.46,
        "mean_reversion_edge_min_margin": 0.06,
    },
    "ont_5m_breakout": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": False,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": True,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.52,
        "entry_prob_buffer": 0.008,
        "entry_min_volume_ratio": 0.98,
        "entry_max_atr_pct": 0.016,
        "breakout_max_bb_width": 0.032,
        "breakout_min_breakout_up_20": 0.0006,
        "breakout_min_volume_ratio": 1.00,
        "breakout_min_close_location": 0.58,
        "breakout_min_range_efficiency": 0.42,
        "breakout_min_signed_volume_proxy": 0.04,
        "breakout_min_price_vs_ema20": 0.0,
        "breakout_prob_floor": 0.53,
    },
    "ont_15m_breakout": {
        "research_interval": "15m",
        "target_horizon_bars": 3,
        "walkforward_train_bars": 144,
        "walkforward_test_bars": 48,
        "walkforward_step_bars": 24,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": False,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": True,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.48,
        "entry_prob_buffer": 0.004,
        "entry_min_volume_ratio": 0.82,
        "entry_max_atr_pct": 0.020,
        "breakout_max_bb_width": 0.040,
        "breakout_min_breakout_up_20": 0.0008,
        "breakout_min_volume_ratio": 0.95,
        "breakout_min_close_location": 0.48,
        "breakout_min_range_efficiency": 0.38,
        "breakout_min_signed_volume_proxy": 0.02,
        "breakout_min_price_vs_ema20": -0.0002,
        "breakout_prob_floor": 0.46,
    },
    "ont_15m_pullback": {
        "research_interval": "15m",
        "target_horizon_bars": 2,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": True,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": False,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.50,
        "entry_prob_buffer": 0.004,
        "entry_min_volume_ratio": 0.88,
        "entry_max_atr_pct": 0.018,
        "mean_reversion_prob_floor": 0.52,
        "mean_reversion_rsi_max": 42.0,
        "mean_reversion_bb_pos_max": 0.22,
        "mean_reversion_range_pos_max": 0.28,
        "mean_reversion_return_5_min": -0.004,
        "mean_reversion_atr_pct_max": 0.018,
        "mean_reversion_rsi_delta_min": 1.0,
        "mean_reversion_body_pct_min": 0.10,
        "mean_reversion_lower_wick_min": 0.20,
        "mean_reversion_price_vs_ema20_max": -0.0015,
        "mean_reversion_min_close_location": 0.38,
        "mean_reversion_min_signed_volume_proxy": 0.00,
        "mean_reversion_min_prob_up": 0.56,
        "mean_reversion_min_model_prob_up": 0.40,
        "mean_reversion_edge_min_margin": 0.03,
    },
    "eth_5m_pullback": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": True,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": False,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.55,
        "entry_prob_buffer": 0.008,
        "entry_min_volume_ratio": 0.92,
        "entry_max_atr_pct": 0.012,
        "mean_reversion_prob_floor": 0.59,
        "mean_reversion_rsi_max": 40.0,
        "mean_reversion_bb_pos_max": 0.18,
        "mean_reversion_range_pos_max": 0.24,
        "mean_reversion_return_5_min": -0.006,
        "mean_reversion_atr_pct_max": 0.012,
        "mean_reversion_rsi_delta_min": 1.4,
        "mean_reversion_body_pct_min": 0.16,
        "mean_reversion_lower_wick_min": 0.28,
        "mean_reversion_price_vs_ema20_max": -0.002,
        "mean_reversion_min_close_location": 0.42,
        "mean_reversion_min_signed_volume_proxy": 0.02,
        "mean_reversion_min_prob_up": 0.60,
        "mean_reversion_min_model_prob_up": 0.44,
        "mean_reversion_edge_min_margin": 0.05,
    },
    "eth_5m_continuation": {
        "research_interval": "5m",
        "target_horizon_bars": 3,
        "btc_mean_reversion_only": False,
        "mean_reversion_enabled": False,
        "allow_countertrend_reversion": False,
        "require_trend_alignment": True,
        "require_nonnegative_rl": False,
        "block_dowtrend_longs": True,
        "entry_score_threshold": 0.54,
        "entry_prob_buffer": 0.008,
        "entry_min_volume_ratio": 1.00,
        "entry_max_atr_pct": 0.011,
        "breakout_max_bb_width": 0.024,
        "breakout_min_breakout_up_20": 0.0009,
        "breakout_min_volume_ratio": 1.00,
        "breakout_min_close_location": 0.60,
        "breakout_min_range_efficiency": 0.45,
        "breakout_min_signed_volume_proxy": 0.08,
        "breakout_min_price_vs_ema20": 0.0001,
        "breakout_prob_floor": 0.57,
    },
}


def profile_names() -> tuple[str, ...]:
    return tuple(PROFILE_OVERRIDES.keys())


def get_profile_overrides(profile_name: str | None) -> dict[str, object]:
    if not profile_name:
        return {}
    return dict(PROFILE_OVERRIDES.get(profile_name, {}))


@contextmanager
def apply_research_profile(profile_name: str | None):
    overrides = get_profile_overrides(profile_name)
    if not overrides:
        yield
        return

    original = {key: getattr(SETTINGS, key) for key in overrides}
    try:
        for key, value in overrides.items():
            setattr(SETTINGS, key, value)
        yield
    finally:
        for key, value in original.items():
            setattr(SETTINGS, key, value)
